server:
    port: 8080
    servlet:
        session:
            persistent: false
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
    servlet:
        multipart:
            enabled: false
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

security:
    basic:
        enabled: false