server:
    port: 8080
    servlet:
        session:
            persistent: false

spring:
    servlet:
        multipart:
            enabled: false
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true